name: handyman_admin_flutter
description: A new Flutter project.

publish_to: 'none'

version: 3.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  nb_utils: ^6.0.2
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  cached_network_image: ^3.2.3
  google_fonts: ^5.1.0
  html: ^0.15.1
  http: ^1.1.0
  intl: ^0.18.0
  url_launcher: ^6.1.12
  flutter_vector_icons: ^2.0.0
  flutter_svg: ^2.0.7
  share_plus: ^7.0.2

  #Firebase
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_remote_config: ^4.2.4

  auto_size_text: 3.0.0
  flutter_custom_tabs: ^1.0.4
  dotted_border: ^2.0.0+3

  #image:
  path_provider: ^2.0.15
  image_picker: ^1.0.1
  multi_image_picker: ^4.8.1
  photo_view: ^0.14.0
  file_picker: ^5.3.3
  lottie: ^2.5.0

  #notifications:
  onesignal_flutter: ^3.5.1

  # Other
  flutter_html: ^3.0.0-alpha.5

  #map:
  google_maps_flutter: ^2.4.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0

  permission_handler: ^10.4.3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/
    - assets/icons/
    - assets/lottie/

